### ISSUE TITLE
[FEATURE] Store Bookmarks and notes to supabase 

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/gita-frontend-v2#100]
### ⭐ Suggestion

We'll need to store user specific data to supabase 
this would include 
- Bookmarks
- Notes
- user Preferences

**Comment by TiwariAbhishek23** [comment]
I am ready to contribute

**Comment by TiwariAbhishek23** [comment]
@akshitarora921, hello, sir, I created 2 issues, #423 and #422, on the Bhagavad Gita page. please have a look, my setup is ready to contribute
