### ISSUE TITLE
More dropdown went under chapter in small screen

### ISSUE THREAD

**Issue by surya-doc** [gita/gita-frontend-v2#101]
### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/69008196/194876902-14b156e9-cfd7-4107-aa90-167a4023a2ba.png)
* On the small screen the "more" dropdown is hiding under the chapter div.

### 🙂 Expected behavior

* The more dropdown should appear over all divs on click.

### 🔢 Steps to Reproduce the Problem

Want to work on this issue. Please assign this to me.

**Comment by tiluckdave** [comment]
@Gupta-Anubhav12 @akshitarora921 
Hey guys I would want to fix this small bug!
May I please get assigned?

**Comment by akshitarora921** [comment]
Hi @tiluckdave, 
Thanks for showing interest but @surya-doc raised this issue and want to work on the same. So, will assign the same to him first.
