### ISSUE TITLE
feat: Scroll to top button

### ISSUE THREAD

**Issue by Rancho2002** [gita/gita-frontend-v2#103]
### ⭐ Suggestion

I want add a <b>back to top</b> button in this page. Please assign me this issue. 
![image](https://user-images.githubusercontent.com/92109154/196022185-33c04073-36df-4aa5-bab7-3a2d9f0fb8fa.png)

**Comment by akshitarora921** [comment]
Hi @Rancho2002, It is a good feature to have. Let's wait for @Gupta-Anubhav12 comments.

**Comment by Rancho2002** [comment]
> Hi @Rancho2002, It is a good feature to have. Let's wait for @Gupta-Anubhav12 comments.

I have started doing it. Eagerly waiting  @akshitarora921

**Comment by Rancho2002** [comment]
hi @akshitarora921 , I have followed all the readme, but the website does not appear well to me, pls look into it and guide 

![image](https://user-images.githubusercontent.com/92109154/196025687-0850fde3-90c2-4fd4-bdae-c161384610be.png)

**Comment by akshitarora921** [comment]
I have re cloned the code and tried, working fine for me. @Rancho2002, Let's connect on discord.

**Comment by Rancho2002** [comment]
> I have re cloned the code and tried, working fine for me. @Rancho2002, Let's connect on discord.

sure, pls give the discord URL and your username

**Comment by akshitarora921** [comment]
Bhagavad Gita Discord [Link](https://discord.gg/v55pa3MC)

**Comment by chiraglal** [comment]
the discord link has expired can you send it again please?

**Comment by akshitarora921** [comment]
https://discord.gg/2NBMbK5w

**Comment by samanyougarg** [comment]
Anyone else who wants to pick this up?
