### ISSUE TITLE
[BUG] Fix Language buttons from footer

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/gita-frontend-v2#104]
### 🙁 Actual behavior

these are redundant and non functional right now giving error on clicking

### 🙂 Expected behavior

better to remove untill we add machine translated strings

**Comment by anshul137** [comment]
hello, i can help  you with this issue if it still open @Gupta-Anubhav12

**Comment by anshul137** [comment]
send the [PR](https://github.com/gita/bg-frontend/pull/113) for review, 
let me know if I need to  update anything.
Thanks
