### ISSUE TITLE
[FEATURE] update contribution.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [gita/gita-frontend-v2#108]
### ⭐ Suggestion

change from 
If you had any issues, bugs, or want to share about your experience, feel free to do so on our GitHub issues page or at our [Discord channel](https://discord.gg/gX8dstApZX).
to
If you had any issues, bugs, or want to share about your experience, feel free to do so on our [GitHub issues page]( https://github.com/gita/bg-frontend/issues/new/choose) or at our [Discord channel](https://discord.gg/gX8dstApZX).

**Comment by Athi223** [comment]
Hey, I'd like to contribute to this
