### ISSUE TITLE
[BUG] validation bug in subscription section

### ISSUE THREAD

**Issue by saimaheshtaduri** [gita/gita-frontend-v2#110]
### 🙁 Actual behavior

When I press subscribe button without entering the form inputs, it isn't showing anything.

### 🙂 Expected behavior

Its better if its tells that both the inputs are required like a error message.

### 🔢 Steps to Reproduce the Problem

1. press subscribe button putting both inputs as blank.

**Comment by akshatj2209** [comment]
Hi, The Bug has been resolved in the latest pull request. Kindly check and close the issue if it seems fine.
