### ISSUE TITLE
[FEATURE] Update Netlify URL

### ISSUE THREAD

**Issue by Athi223** [gita/gita-frontend-v2#116]
### ⭐ Suggestion

The Netlify URL can be updated to something like **bhagawad-gita.netlify.app** instead of the current _vague_ URL, especially since this option is available free of cost.

### 💻 Use Cases

A meaningful URL can be provided in README as well as socials if required

**Comment by itsBaivab** [comment]
I want to fix this issue can you please assing this to me

**Comment by shivam-jha2712** [comment]
> ### ⭐ Suggestion
> The Netlify URL can be updated to something like **bhagawad-gita.netlify.app** instead of the current _vague_ URL, especially since this option is available free of cost.
> 
> ### 💻 Use Cases
> A meaningful URL can be provided in README as well as socials if required
> 
> ### ❌ Related Problems
> _No response_

I would like to work on this issue for WOC 3.0

**Comment by sabhisharma-ise** [comment]
Hey Can you Assign this issue (For Winter of Code 3.0)
