### ISSUE TITLE
[BUG] Center align the copyright message on the footer

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#127]
### 🙁 Actual behavior

<img width="1920" alt="Screenshot 2023-06-12 at 11 58 11 AM" src="https://github.com/gita/bg-frontend/assets/32533774/c7930b8f-0814-40d1-9cd2-45e7ff94478f">

### 🙂 Expected behavior

Center align it.

**Comment by Alok-1512** [comment]
Hey I would like to work on this issue

**Comment by samanyougarg** [comment]
Sure, please pick it up @Alok-1512

**Comment by eht-ck** [comment]
@samanyougarg I would like to work on this issue

**Comment by eht-ck** [comment]
Issue resolved in #150
