### ISSUE TITLE
[BUG] All external links should open in new tabs

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#128]
### 🙁 Actual behavior

<img width="609" alt="Screenshot 2023-06-12 at 11 59 04 AM" src="https://github.com/gita/bg-frontend/assets/32533774/a0c49972-3744-42c9-8f15-64b51f0003fc">

All these lines are opening in the same tab and taking the user away from the site.

### 🙂 Expected behavior

Apart from any BG internal links like about us page, all others ones should open in new tabs.
**Also, hide the Press button since it doesn't have any link associated.**

**Comment by Alok-1512** [comment]
I would like to work on this issue

**Comment by samanyougarg** [comment]
Sure, please feel free to pick up and send a PR

**Comment by samanyougarg** [comment]
Fixed in #148
