### ISSUE TITLE
[BUG] Add iOS app link as well

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#129]
### 🙁 Actual behavior

Only play store button is showing. We also have an IOS app. 

### 🙂 Expected behavior

![image](https://github.com/gita/bg-frontend/assets/32533774/53b7da97-3918-4cf6-8bd2-c9f60edfa865)

Add the button for iOS as well and link to: https://apps.apple.com/us/app/bhagavad-gita-hindi-english/id1602895635

**Comment by eht-ck** [comment]
Issue resolved in #150
