### ISSUE TITLE
Bug: Outline Borders 

### ISSUE THREAD

**Issue by ayushsoni1010** [gita/gita-frontend-v2#13]
Hey Anubhav👋
I would like to remove all the unwanted outline borders for more UX friendly

**Comment by akshitarora921** [comment]
Hi @ayushsoni1010, this is not a bug, this is an important part of accessibility and removing it makes it difficult for keyboard users to navigate a site.
[source](https://betterprogramming.pub/a11y-never-remove-the-outlines-ee4efc7a9968)

**Comment by ayushsoni1010** [comment]
Thanks for sharing man!

> Hi @ayushsoni1010, this is not a bug, this is an important part of accessibility and removing it makes it difficult for keyboard users to navigate a site. [source](https://betterprogramming.pub/a11y-never-remove-the-outlines-ee4efc7a9968)
