### ISSUE TITLE
[BUG] Navbar icons should all be same size

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#137]
### 🙁 Actual behavior

<img width="628" alt="Screenshot 2023-06-12 at 12 14 30 PM" src="https://github.com/gita/bg-frontend/assets/32533774/a68658d5-a245-46f4-b4c6-0c00cd5b2867">

Currently, some are bigger and some are smaller.

### 🙂 Expected behavior

Navbar icons should all be same size.

**Comment by Alok-1512** [comment]
I would like to work on this issue

**Comment by samanyougarg** [comment]
Sure, please pick it up @Alok-1512
