### ISSUE TITLE
[BUG] Improve text formatting on verse page

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#139]
### 🙁 Actual behavior

<img width="1194" alt="Screenshot 2023-06-12 at 12 17 22 PM" src="https://github.com/gita/bg-frontend/assets/32533774/96f9a436-c71a-41d3-89d2-7534770d19de">

Text is quite hotchpotch and hard to read.

### 🙂 Expected behavior

<img width="1032" alt="Screenshot 2023-06-12 at 12 17 56 PM" src="https://github.com/gita/bg-frontend/assets/32533774/eaba0677-8a65-4a85-ac5e-7f90d5b513fb">

Add proper headings, spacing in between text and proper text styles to make it easy on the eye. Please see only the layout for reference and not the actual colors.

**Comment by anoopg512** [comment]
I have formatted the code by adding appropriate indentation and line breaks to improve readability.

Here's the code from version #139 with improved formatting and readability:
import { connect } from "react-redux";
import NotificationBanner from "./Shared/NotificationBanner";

const Main = ({ Component, pageProps, notification }) => {
  const getLayout = Component.getLayout || ((page) => page);

  return (
    <>
      {notification && (
        <NotificationBanner
          message={notification.message}
          status={notification.status}
        />
      )}
      {getLayout(<Component {...pageProps} />)}
    </>
  );
};

const mapStateToProps = (state) => {
  return {
    notification: state.main?.notification,
  };
};

export default connect(mapStateToProps)(Main);

**Comment by samanyougarg** [comment]
@anoopg512 can you please make a PR?
