### ISSUE TITLE
[BUG] next/previous buttons are too far away on quotes page

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#145]
### 🙁 Actual behavior

<img width="1911" alt="Screenshot 2023-06-12 at 12 32 14 PM" src="https://github.com/gita/bg-frontend/assets/32533774/986a993f-ad6f-4f39-82b2-c2e3a5fba2e2">

- [ ] next/previous buttons are too far away on quotes page
- [ ] Also, here we have 100+ shlokas: https://bhagavadgita.io/bhagavad-gita-quotes/ but we have only implemented like 25 of them.

### 🙂 Expected behavior

See above.

**Comment by the-akleem91** [comment]
Can I solve this issue ?

**Comment by samanyougarg** [comment]
Sure @the-akleem91
