### ISSUE TITLE
[FEATURE] Save user's name and email for newsletter subscription in a new table in the db

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#165]
### ⭐ Suggestion

<img width="1106" alt="Screenshot 2023-07-09 at 6 28 02 PM" src="https://github.com/gita/gita-frontend-v2/assets/32533774/76cd8d47-e4c8-4299-bb1f-62610b5e8a9b">

Save the data from this form in a new `newsletter_subscriptions` table in the db using graphql.

**Comment by eht-ck** [comment]
I would like to work on this issue.

**Comment by samanyougarg** [comment]
Sure, are you clear on this or need more details. Can you please ping me on Slack? Will share Hasura creds.
