### ISSUE TITLE
[FEATURE] Switch all GraphQL endpoints to Hasura

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#167]
### ⭐ Suggestion

We need to switch all the GraphQL endpoints to Hasura similar to `pages/index.js`. Also, we should define a global client instead of recreating the client in every file.

**Comment by eht-ck** [comment]
I would like to work on this issue but need some guidance and help intially to get started with this issue.

**Comment by samanyougarg** [comment]
@eht-ck This has been done by Oleh in #175 so you can please focus on other tasks.
