### ISSUE TITLE
[BUG] Chapter page issues

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#188]
1. Verse selection dropdown on chapters page is too big.
<img width="388" alt="Screenshot 2023-08-16 at 1 19 02 AM" src="https://github.com/gita/gita-frontend-v2/assets/32533774/35649c37-c8e0-49fc-b0b5-f131d5616cb6">

2. Also, the verse numbers are not aligned here. There's too much space on the right side.
<img width="495" alt="Screenshot 2023-08-16 at 1 19 54 AM" src="https://github.com/gita/gita-frontend-v2/assets/32533774/0577e35e-2558-4cf6-8a90-7e9d5fa05f6a">

3. Clicking outside the verse selection box should close it.
<img width="620" alt="Screenshot 2023-08-16 at 1 21 29 AM" src="https://github.com/gita/gita-frontend-v2/assets/32533774/b174d5cf-330e-449b-bb57-8850ff70cdfc">

4. Clicking on some verse number should directly open that verse page.
<img width="460" alt="Screenshot 2023-08-16 at 1 22 06 AM" src="https://github.com/gita/gita-frontend-v2/assets/32533774/9a602e98-e7a3-4580-952b-0157ca49223f">

**Comment by shantanusoni72** [comment]
I am working on it

**Comment by samanyougarg** [comment]
Fixed in #245
