### ISSUE TITLE
[RELEASE] App page

### ISSUE THREAD

**Issue by samanyougarg** [gita/gita-frontend-v2#195]
### ⭐ Suggestion

We have an app page https://bhagavadgita.io/app on the old site and need a similar one here on the Next app.

Instead of creating this page from scratch, can we copy the HTML code of that page from the previous site and reverse proxy the `/app` URL on the Next site?

**Comment by anrag** [comment]
Can I take this UP ?

**Comment by the-akleem91** [comment]
I want to contribute to developed this page, I already tried to solve this But in my local machine it did not run
