### ISSUE TITLE
Suggest contributions 

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/gita-frontend-v2#2]
Since we are participating in Winter of Code, so we are inviting open source enthusiasts to contribute to the project,
@arjitvermaco  @samanyougarg  please list out some tasks and issues to be solved, some pages to be made or anything that has to be done or is left behind, 
we'll start the coding phase by 30th november, 
Please get some issues, refinements, anything desired to be accoplished by then

Thanks 
Hare Krishna

**Comment by akshitarora921** [comment]
@Gupta-Anubhav12 Great. I will love to contribute. 
Also, can you please share the Figma design as mentioned in the idealist on the WOC website?
![Screenshot from 2021-11-13 19-52-21](https://user-images.githubusercontent.com/11087313/141647396-42a669f9-a5c4-4e67-8c74-9e0973d3e5b6.png)

**Comment by Gupta-Anubhav12** [comment]
https://www.figma.com/file/hzQx3sxi0ClbpTCMH2gi1F/Bhagavad-Gita-App-(Editable)?node-id=919%3A504
https://www.figma.com/file/pBIgtdAmP7SRyy3SGsJPhP/Website?node-id=125%3A1580
 The mvp will be launched in a day or two, It got delayed a bit 
you can mention bugs and fixes in proposal doc meanwhile we get the repo ready for contributions

**Comment by akshitarora921** [comment]
@arjitvermaco I have uploaded a generic proposal (before figma designs) saying I will contribute in making new components? Should I raise another proposal? If yes then how?
Also raised a PR regarding issue I faced during project setup at my local computer.

**Comment by Gupta-Anubhav12** [comment]
Can I have a look at the proposal 
You can mail me a copy at anubhavgupta2260@gmail.com

**Comment by akshitarora921** [comment]
Sure @Gupta-Anubhav12
