### ISSUE TITLE
[BUG] Overflow of quotes content for large quotes in mobile view.

### ISSUE THREAD

**Issue by eht-ck** [gita/gita-frontend-v2#216]
### 🙁 Actual behavior

Overflow of quote content over footer.
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/89501333-98ca-4eb6-a844-305a22a52db0)

### 🙂 Expected behavior

Div container should be flexible when quote content is more it should increase container size to avoid content overflow.

**Comment by NawinKumarSharma** [comment]
can i word on this? please assign

**Comment by nawinsharma** [comment]
can you please assign me?

**Comment by eht-ck** [comment]
@NawinKumarSharma Yes sure,  please pick this up.

**Comment by nawinsharma** [comment]
@eht-ck  Hey, I have made changes and it is fixed now .please review my Pull Request.
Final look:
![image](https://github.com/gita/gita-frontend-v2/assets/126372969/00ce9e97-4e8d-442c-9352-954be7c69c48)

**Comment by nawinsharma** [comment]
https://github.com/gita/gita-frontend-v2/pull/225
