### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by sarthak-kumar-shailendra** [gita/gita-frontend-v2#221]
### ⭐ Suggestion

Issue Description
The Twitter logo has been updated recently and hasn't been updated on the site. 

Steps to Reproduce
Step 1: Go to footer section and see twitter old lcon
Expected Behavior
The Twitter logo should be changed to X.
<img width="160" alt="Screenshot 2023-09-15 at 1 50 29 AM" src="https://github.com/gita/gita-frontend-v2/assets/69191344/d318cc98-6eb8-44ed-adfc-ee005992e93d">

**Comment by samanyougarg** [comment]
@sarthak-kumar-shailendra could you please help make a PR?

**Comment by sarthak-kumar-shailendra** [comment]
yes, will do @samanyougarg

**Comment by sarthak-kumar-shailendra** [comment]
@samanyougarg request you to check my others 2 PRs as well

**Comment by samanyougarg** [comment]
Sure will check
