### ISSUE TITLE
[BUG] Color buttons in appearance setting not working

### ISSUE THREAD

**Issue by shantanu-wdev** [gita/gita-frontend-v2#231]
### 🙁 Actual behavior

These color buttons are not working except black button. 
![image](https://github.com/gita/gita-frontend-v2/assets/75296055/13458c2c-2aae-4908-ad52-252a332062e3)

### 🙂 Expected behavior

It should change the theme as according to color selected.

### 🔢 Steps to Reproduce the Problem

1. Go to any chapter page.
2. Click at Appearance Settings
3. Select either white or light yellow color and apply
4. Nothing happens

**Comment by PALLAVIKHEDLE** [comment]
Can you please assign this issue to me?

**Comment by shantanu-wdev** [comment]
> Can you please assign this issue to me?

Yes.

**Comment by shantanu-wdev** [comment]
According to their business logic, the dark theme is activated when setTheme('dark') is executed with the 'bg-dark-bg' value matched otherwise it will activate the light theme by default. This is because they are using default themes of the next-theme library for applying themes. I wonder if I remove the yellow button then this issue can be resolved. Should I do it?

Is it good enough?
![image](https://github.com/gita/gita-frontend-v2/assets/75296055/baffa4c8-607e-452b-998d-bb414c5071cf)
