### ISSUE TITLE
dark mode support

### ISSUE THREAD

**Issue by akshitarora921** [gita/gita-frontend-v2#32]
### ⭐ Suggestion

Add support for dark mode

**Comment by redraushan** [comment]
Hi @akshitarora921, hope you're doing great. To me looks like dark-mode related work has been done. Do you think anything left? Happy to contribute if something left. Cheers

**Comment by akshitarora921** [comment]
Hi @redraushan, newsletter component on the homepage is pending. If you want, you can take it up.
Thank you for the contribution 🌸 .
