### ISSUE TITLE
Add content to Readme.md and make a Contributing.md

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/gita-frontend-v2#4]

**Comment by akshitarora921** [comment]
@Gupta-Anubhav12 Can I take this?

**Comment by Gupta-Anubhav12** [comment]
Sure 
It'd be a great help, do add AllContributors bot and all necessary docs for setup of the repo

**Comment by Gupta-Anubhav12** [comment]
https://github.com/gita/bhagavad-gita-api#readme

use this format

**Comment by harshita214** [comment]
@Gupta-Anubhav12 hey can I do contributing.md if it's alright with @Gupta-Anubhav12 @akshitarora921 :)

**Comment by akshitarora921** [comment]
@harshita214 Sure, we can split I will do readme.md and you can do contribution.md

**Comment by ayushsoni1010** [comment]
Hey @Gupta-Anubhav12 👋
I would like to work on contributing.md , if @harshita214 is not working on it, can you assign me this issue?

**Comment by harshita214** [comment]
Hey @ayushsoni1010 working on it, will submit a PR soon

**Comment by ayushsoni1010** [comment]
No worries @harshita214 :)
Go ahead🚀
