### ISSUE TITLE
[FEATURE] Add search Functionality to Frontend

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/gita-frontend-v2#78]
### ⭐ Suggestion

We added search endpoint to the rest API 
```
curl -X 'GET' \
  'https://api.bhagavadgita.io/v2/search?query=Karma' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: <API-KEY>'
  
```

would be good to add search to frontend

Current Implementation 
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/11087313/193606776-48c40b6a-39e7-474d-8efc-99b10825d83e.png">

Required:
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/11087313/193606988-f186edd7-f25b-4f94-a79e-e1b847a1e303.png">

Also, before creating pull Request, check the functionality working across all the headers.

**Comment by redraushan** [comment]
Hi @Gupta-Anubhav12, any idea if we already have figma designs for "Search Result" component? Thanks

**Comment by Gupta-Anubhav12** [comment]
Hii for sure 
https://www.figma.com/file/jssDxh7avC7hkq7Wl9CZEY/Gita-Web-App?node-id=0%3A1

Here are complete designs for frontend app

**Comment by redraushan** [comment]
Hi @Gupta-Anubhav12, @ankitach23, do you mind if I take this one and start working right away? Feel free to assign this to me if that's fine otherwise I am happy with another ticket if that's more prior to this, thanks.

**Comment by akshitarora921** [comment]
Hi @redraushan, Let me know if you are still available to take this issue, Happy to assign it to you. :)

**Comment by Gupta-Anubhav12** [comment]
Hey Search thing was already done
so closing this
