### ISSUE TITLE
[FEATURE] Implement Authentication using SupaBase

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/gita-frontend-v2#99]
### ⭐ Suggestion

We do have login/Signup pages but we need to add user authentication using Supabase say to store user data

**Comment by bkjain655** [comment]
Hi @Gupta-Anubhav12 ,

I can work on this feature request. Can you please share the complete details for this?

**Comment by TiwariAbhishek23** [comment]
I am also ready with my setup

**Comment by utkershrajvenshi** [comment]
Hey @akshitarora921 @Gupta-Anubhav12 . I would love to have a go at this. Could you please assign me to this issue?
